config/routes.rb
Ddnext::Application.routes.draw do
  resources :game_classes
  resources :races
  resources :subraces
  resources :characters
  resources :character_classes

  patch "characters/:id/remove_class_level" => 'characters#remove_class_level'
  patch "characters/:id/add_class_level" => 'characters#add_class_level'

  patch "subraces/:id/update_feature" => 'subraces#update_to_add_feature'
  patch "races/:id/update_feature" => 'races#update_to_add_feature'

  patch "subraces/:id/add_feature" => 'subraces#new_to_add_feature'
  patch "races/:id/add_feature" => 'races#new_to_add_feature'

  patch "subraces/:id/remove_feature" => 'subraces#remove_to_add_feature'
  patch "races/:id/remove_feature" => 'races#remove_to_add_feature'

  

end

app/models/race.rb
class Race
  include MongoMapper::Document

  #association
  many :subraces

  #embedded Docs
  many :to_add_features

  #callbacks
  before_create :initalize_features

  #fields
  key :title
  key :description

  private

  def initalize_features
    self.to_add_features << ToAddFeature.new(title: "", type: "", category: "", subcategory: "", value: "", requirements: [], notes: "")
  end

end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index
    @races = Race.all
  end

  def new
    @race = Race.new()
  end

  def create
    @race = Race.new(race_params)
    if @race.save
      redirect_to races_path(), notice: "Created Race"
    else
      flash[:alert] = "Unable to create race"
      render 'new'
    end
  end

  def show
    @race = Race.find(params[:id])
  end

  def edit
    @race = Race.find(params[:id])
  end

  def update
    @race = Race.find(params[:id])
    respond_to do |format|
      if @race.update_attributes(race_params)
        responce = {race: @race}
        format.html {redirect_to @race, notice: "Updated Race"}
        format.json {render json: responce, status: :created, location: responce}
      else
        format.html {
          flash[:alert] = "Unable to update race"
           render "edit"
        }
      end
    end
  end

  def destroy
    @race = Race.find(params[:id])
    if @race.destory
      redirect_to race_path(), notice: "Race Destoryed"
    else
      redirect_to @race, alert: "Unable to destory race"
    end
  end

  def update_to_add_feature
    race = Race.find(params[:id])
    feature = race.to_add_features.find(race_params["id"])
    feature.update_attributes(race_params)
    race = Race.find(params[:id])
    respond_to do |f|
      responce = {race: race}
      f.json {render json: responce, status: :created, location: responce}
    end
  end

  def new_to_add_feature
    race = Race.find(params[:id])
    race.to_add_features << ToAddFeature.new(title: "", type: "", category: "", subcategory: "", value: "", requirements: [], notes: "")
    race.save
    race = Race.find(params[:id])
    respond_to do |f|
      responce = {race: race}
      f.json {render json: responce, status: :created, location: responce}
    end
  end

  def remove_to_add_feature
    race = Race.find(params[:id])
    race.to_add_features.delete_if do |feature|
      feature.id.to_s == race_params["id"]
    end
    race.save
    race = Race.find(params[:id])
    respond_to do |f|
      responce = {race: race}
      f.json {render json: responce, status: :created, location: responce}
    end
  end

  def race_params
    JSON.parse(params.required(:race))
  end
end

app/views/races/_form.html.haml
= simple_form_for @race do |f|
  = f.input :title
  = f.input :description
  = f.submit

app/views/races/edit.html.haml
%h1 Edit Race
= render 'form'

app/views/races/index.html.haml
%h1 All Races
=link_to "Create New Race", new_race_path()
- unless @races.empty?
  %table
    %tr
      %th Race
      %th Actions
    - @races.each do |race|
      %tr
        %td= race.title
        %td= " #{link_to 'View', race} | #{link_to 'Edit', edit_race_path(race)}".html_safe

app/views/races/new.html.haml
%h1 Create Race
= render 'form'

app/views/races/show.html.haml
#page

- content_for :page_javascript do
  = javascript_include_tag (asset_path("race.js"))

#baked_in_javascript
  :javascript
    var baked = {
      race: #{@race.to_json},
      subraces: #{@subraces.to_json},
      url: "#{ENV['ROOT']}/races/#{params[:id]}"
    }