config/routes.rb
Ddnext::Application.routes.draw do
  resources :game_classes
  resources :races
  resources :subraces
  resources :characters
  resources :character_classes

  patch "characters/:id/remove_class_level" => 'characters#remove_class_level'
  patch "characters/:id/add_class_level" => 'characters#add_class_level'

  patch "subraces/:id/update_feature" => 'subraces#update_to_add_feature'
  patch "races/:id/update_feature" => 'races#update_to_add_feature'

  patch "subraces/:id/add_feature" => 'subraces#new_to_add_feature'
  patch "races/:id/add_feature" => 'races#new_to_add_feature'

  patch "subraces/:id/remove_feature" => 'subraces#remove_to_add_feature'
  patch "races/:id/remove_feature" => 'races#remove_to_add_feature'

  

end

app/controllers/game_classes_controller.rb
class GameClassesController < ApplicationController

  def index
    @classes = GameClass.all
  end

  def new
    @class = GameClass.new()
  end

  def create
    @class = GameClass.new(class_params)
    if @class.save
      redirect_to game_classes_path(), notice: "Created Class"
    else
      flash[:alert] = "Unable to create class"
      render 'new'
    end
  end

  def show
    @class = GameClass.find(params[:id])
  end

  def edit
    @class = GameClass.find(params[:id])
  end

  def update
    @class = GameClass.find(params[:id])
    if @class.update_attributes(class_params)
      redirect_to @class, notice: "Updated Class"
    else
      flash[:alert] = "Unable to update class"
      render "edit"
    end
  end

  def destroy
    @class = GameClass.find(params[:id])
    if @class.destory
      redirect_to game_classes_path(), notice: "Classes Destoryed"
    else
      redirect_to @class, alert: "Unable to destory class"
    end
  end

  def class_params
    params.required(:game_class).permit(:title, :description)
  end
end

app/helpers/game_classes_helper.rb
module GameClassesHelper
end

app/views/game_classes/_form.html.haml
= simple_form_for @class do |f|
  = f.input :title
  = f.input :description
  = f.submit

app/views/game_classes/edit.html.haml
%h1 Edit Class
= render 'form'

app/views/game_classes/index.html.haml
%h1 All Classes
=link_to "Create New Class", new_game_class_path()
- unless @classes.empty?
  %table
    %tr
      %th Class
      %th Actions
    - @classes.each do |gclass|
      %tr
        %td= gclass.title
        %td= " #{link_to 'View', gclass} | #{link_to 'Edit', edit_game_class_path(gclass)}".html_safe

app/views/game_classes/new.html.haml
%h1 Create Race
= render 'form'

app/views/game_classes/show.html.haml
%h1= @class.title
%p= @class.description