config/routes.rb
Ddnext::Application.routes.draw do
  resources :game_classes
  resources :races
  resources :subraces
  resources :characters
  resources :character_classes

  patch "characters/:id/remove_class_level" => 'characters#remove_class_level'
  patch "characters/:id/add_class_level" => 'characters#add_class_level'

  patch "subraces/:id/update_feature" => 'subraces#update_to_add_feature'
  patch "races/:id/update_feature" => 'races#update_to_add_feature'

  patch "subraces/:id/add_feature" => 'subraces#new_to_add_feature'
  patch "races/:id/add_feature" => 'races#new_to_add_feature'

  patch "subraces/:id/remove_feature" => 'subraces#remove_to_add_feature'
  patch "races/:id/remove_feature" => 'races#remove_to_add_feature'

  

end

app/models/subrace.rb
class Subrace
  include MongoMapper::Document

  many :to_add_features

  belongs_to :race

  before_save :set_race_title

  before_create :initalize_features

  key :title
  key :description
  key :race_title

  def update_feature(update)
  end

  private

  def initalize_features
    self.to_add_features << ToAddFeature.new(title: "", type: "", category: "", subcategory: "", value: "", requirements: [], notes: "")
  end

  def set_race_title
    self.race_title = self.race.title
  end
end

app/controllers/subraces_controller.rb
class SubracesController < ApplicationController

  def index
    @subraces = Subrace.all
  end

  def new
    @subrace = Subrace.new()
  end

  def create
    @subrace = Subrace.new(subrace_params)
    if @subrace.save
      redirect_to subraces_path(), notice: "Created Subrace"
    else
      flash[:alert] = "Unable to create subrace"
      render 'new'
    end
  end

  def show
    @subrace = Subrace.find(params[:id])
  end

  def edit
    @subrace = Subrace.find(params[:id])
  end

  def update
    @subrace = Subrace.find(params[:id])
    respond_to do |format|
      if @subrace.update_attributes()
        responce = {subrace: @subrace}
        format.html {redirect_to @subrace, notice: "Updated Subrace"}
        format.json {render json: responce, status: :created, location: responce}
      else
        format.html {
          flash[:alert] = "Unable to update subrace"
          render "edit"
        }
      end
    end
  end

  def destroy
    @subrace = Subrace.find(params[:id])
    if @subrace.destory
      redirect_to subrace_path(), notice: "Subrace Destoryed"
    else
      redirect_to @subrace, alert: "Unable to destory subrace"
    end
  end

  def update_to_add_feature
    subrace = Subrace.find(params[:id])
    feature = subrace.to_add_features.find(subrace_params["id"])
    feature.update_attributes(subrace_params)
    subrace = Subrace.find(params[:id])
    respond_to do |f|
      responce = {subrace: subrace}
      f.json {render json: responce, status: :created, location: responce}
    end
  end

  def new_to_add_feature
    subrace = Subrace.find(params[:id])
    subrace.to_add_features << ToAddFeature.new(title: "", type: "", category: "", subcategory: "", value: "", requirements: [], notes: "")
    subrace.save
    subrace = Subrace.find(params[:id])
    respond_to do |f|
      responce = {subrace: subrace}
      f.json {render json: responce, status: :created, location: responce}
    end
  end

  def remove_to_add_feature
    subrace = Subrace.find(params[:id])
    subrace.to_add_features.delete_if do |feature|
      feature.id.to_s == subrace_params["id"]
    end
    subrace.save
    subrace = Subrace.find(params[:id])
    respond_to do |f|
      responce = {subrace: subrace}
      f.json {render json: responce, status: :created, location: responce}
    end
  end

  def subrace_params
    JSON.parse(params.required(:subrace))
  end
end

app/views/subraces/_form.html.haml
= simple_form_for @subrace do |f|
  = select("subrace", "race_id", Race.all.collect {|r| [ r.title, r.id ] })
  = f.input :title
  = f.input :description
  = f.submit

app/views/subraces/edit.html.haml
%h1 Edit Subrace
= render 'form'

app/views/subraces/index.html.haml
%h1 All Subraces
=link_to "Create New Subrace", new_subrace_path()
- unless @subraces.empty?
  %table
    %tr
      %th Subrace
      %th Actions
    - @subraces.each do |subrace|
      %tr
        %td= subrace.title
        %td= " #{link_to 'View', subrace} | #{link_to 'Edit', edit_subrace_path(subrace)}".html_safe

app/views/subraces/new.html.haml
%h1 Create Subrace
= render 'form'

app/views/subraces/show.html.haml
#page

- content_for :page_javascript do
  = javascript_include_tag (asset_path("subrace.js"))

#baked_in_javascript
  :javascript
    var baked = {
      subrace: #{@subrace.to_json},
      races: #{Race.all.to_json},
      url: "#{ENV['ROOT']}/subraces/#{params[:id]}"
    }