config/routes.rb
Ddnext::Application.routes.draw do
  resources :game_classes
  resources :races
  resources :subraces
  resources :characters
  resources :character_classes

  patch "characters/:id/remove_class_level" => 'characters#remove_class_level'
  patch "characters/:id/add_class_level" => 'characters#add_class_level'

  patch "subraces/:id/update_feature" => 'subraces#update_to_add_feature'
  patch "races/:id/update_feature" => 'races#update_to_add_feature'

  patch "subraces/:id/add_feature" => 'subraces#new_to_add_feature'
  patch "races/:id/add_feature" => 'races#new_to_add_feature'

  patch "subraces/:id/remove_feature" => 'subraces#remove_to_add_feature'
  patch "races/:id/remove_feature" => 'races#remove_to_add_feature'

  

end

app/controllers/character_classes_controller.rb
class CharacterClassesController < ApplicationController

  def index
    @char_classes= CharacterClass.all
  end

  def new
    @char_class = CharacterClass.new()
  end

  def create
    @char_class = CharacterClass.new(char_class_params)
    if @char_class.save
      redirect_to character_classes_path(), notice: "Created Chararcter Class"
    else
      flash[:alert] = "Unable to create char_class"
      render 'new'
    end
  end

  def show
    @char_class = CharacterClass.find(params[:id])
  end

  def edit
    @char_class = CharacterClass.find(params[:id])
  end

  def update
    @char_class = CharacterClass.find(params[:id])
    if @char_class.update_attributes(char_class_params)
      redirect_to @char_class, notice: "Updated Chararcter Class"
    else
      flash[:alert] = "Unable to update char_class"
      render "edit"
    end
  end

  def destroy
    #TODO Need to adjust the level to work with the fact that something was removed. 
    @char_class = CharacterClass.find(params[:id])
    if @char_class.destroy
      redirect_to character_class_path(), notice: "Chararcter Class Destoryed"
    else
      redirect_to character_classes_path(), alert: "Unable to destory char_class"
    end
  end

  def char_class_params
    params.required(:character_class).permit(:character_id, :game_class_id)
  end
end

app/views/character_classes/_form.html.haml
= simple_form_for @char_class do |f|
  = f.association :character
  = f.association :game_class
  = f.submit

app/views/character_classes/edit.html.haml
%h1 Edit Character Class
= render 'form'

app/views/character_classes/index.html.haml
%h1 All Character Classes (This view will go away in time)
=link_to "Create New Character Clas", new_character_class_path()
- unless @char_classes.empty?
  %table
    %tr
      %th Character
      %th Class
      %th Actions
    - @char_classes.each do |char_class|
      %tr
        %td= char_class.character.name
        %td= char_class.game_class.title
        %td= " #{link_to 'View', char_class} | #{link_to 'Edit', edit_character_class_path(char_class)}".html_safe

app/views/character_classes/new.html.haml
%h1 Create Character Class
= render 'form'

app/views/character_classes/show.html.haml
%h1= "#{@char_class.character.name} to a level in #{@char_class.game_class.title} at character level #{@char_class.character_level}"
= link_to 'Remove this level and class', character_class_path(@char_class.id), :confirm => 'Are you sure?', :method => :delete 